config/routes.rb
Qcss::Application.routes.draw do

  namespace :silicon_metal do
    resources :gpos
  end

  namespace :silicon_metal do
    resources :pos
  end

  namespace :silicon_metal do
    resources :si_shippings
  end

  namespace :silicon_metal do
    resources :mix_bags
    resources :mix_bag_contents
  end

  namespace :purchase do
    resources :units
  end

  namespace :warehouse do
    resources :checkins
  end

  namespace :hr do resources :subcompanies end

  namespace :hr do resources :positions end

  namespace :hr do resources :dept_changes end

  namespace :ms do resources :bag_inventories end

  namespace :ms do resources :bags end

  namespace :hr do 
    resources :attendences do
      collection { post :import }
      collection do
        get :summary
      end
    end
  end
      
  
  namespace :power do resources :factors end

  namespace :power do resources :furnaces end

  namespace :power do 
    resources :totals do
      collection do
        get :summary
      end
    end 
  end

  namespace :hr do
    resources :otms do
      collection do
        get :summary
      end
    end
  end

  namespace :purchase do resources :locations end

  namespace :purchase do 
    resources :requests do
      collection do
        get :plan
        get :reject
        get :finish
        get :warehouse
        get :warehoused
        get :trace
        get :p_confirm
        get :all
      end
    end
  end
  
  namespace :purchase do resources :request_photos end

  resources :e_furnaces do
    collection do
      get :summary
    end
  end

  resources :rm_rates

  resources :security_case_media

  resources :security_cases

  resources :ms_reworks

  resources :vehicle_requests do
    collection do 
      get :planning
    end
  end

  resources :v_netweights

  resources :vehicle_dailies

  resources :weightings do
    collection do
      get :summary
    end
  end

  resources :vehicles

  resources :dailyreport_jobs

  resources :dailyreports do
    collection do
      get :daily_summary
    end
  end

  namespace :interviews do resources :its end

  resources :destinations

  resources :freights

  resources :payments

  resources :partical_sizes

  resources :po_controls do
    collection do
      get :po_search_result
    end
  end

  resources :ms_offgrades

  resources :si_inventory_contents

  resources :si_inventories do
    collection do
      get :si_inventory_report
      get :multiple_bags
      post :create_multiple
    end
  end

  resources :pickings

  resources :warehouse_item_photos

  resources :employeer_photos

  resources :employeers

  resources :it_reservations

  resources :quartz_photos

  resources :quartzs

  resources :ms_loadings do
    collection do
      get :loading_summary_search_result
    end
  end

  resources :ms_losses

  get "impress/microsilica"

  resources :ms_prod_confirms

  resources :silicashiplots

  resources :silicaships

  resources :sampleresults

  resources :oxygens

  resources :msshipbags

  resources :msshiplots

  resources :ms_shippments

  resources :charcoal_dusts

  resources :mssamples

  resources :samples

  resources :en_certifies

  resources :microsilicas

  resources :silos

  resources :env_monitors

  resources :it_devices

  resources :customers

  resources :complains

  resources :it_repairs

  resources :categories

  resources :departments

  resources :warehouse_suppliers

  resources :warehouse_items

  resources :suppliers

  resources :charcoals

  resources :coasilicons

  get "analysis/silicon"

  get "reports/daily"

  get "reports/period"
  
  get "reports/charcoalsum"

  get "summary/index"

  get "site/index"
  

  devise_for :users
  resources :users 
  resources :grades

  resources :silicons
  resources :coas
  

  root :to => "site#index"

  get ':controller(/:action(/:id(.:format)))'
  
end

app/models/quartz_photo.rb
#coding: utf-8

class QuartzPhoto < ActiveRecord::Base
  
  belongs_to :quartz, :foreign_key=>'quartz_id'
  
  has_attached_file :photo, 
    :url=>"/upload_photos/quartz_photos/:attachment/:quartz_id/:id/:style/:filename", 
    :styles => { :small  => "600x400>", :thumb => "75x50>" }
  validates_attachment_size :photo, :less_than => 10.megabytes
  
end

app/controllers/quartz_photos_controller.rb
class QuartzPhotosController < ApplicationController
  # GET /quartz_photos
  # GET /quartz_photos.xml
  def index
    @quartz_photos = QuartzPhoto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quartz_photos }
    end
  end

  # GET /quartz_photos/1
  # GET /quartz_photos/1.xml
  def show
    @quartz_photo = QuartzPhoto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quartz_photo }
    end
  end

  # GET /quartz_photos/new
  # GET /quartz_photos/new.xml
  def new
    @quartz_photo = QuartzPhoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quartz_photo }
    end
  end

  # GET /quartz_photos/1/edit
  def edit
    @quartz_photo = QuartzPhoto.find(params[:id])
  end

  # POST /quartz_photos
  # POST /quartz_photos.xml
  def create
    params.permit!
    @quartz_photo = QuartzPhoto.new(params[:quartz_photo])

    respond_to do |format|
      if @quartz_photo.save
        format.html { redirect_to(@quartz_photo, :notice => 'Quartz photo was successfully created.') }
        format.xml  { render :xml => @quartz_photo, :status => :created, :location => @quartz_photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quartz_photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quartz_photos/1
  # PUT /quartz_photos/1.xml
  def update
    params.permit!
    @quartz_photo = QuartzPhoto.find(params[:id])

    respond_to do |format|
      if @quartz_photo.update_attributes(params[:quartz_photo])
        format.html { redirect_to(@quartz_photo, :notice => 'Quartz photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quartz_photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quartz_photos/1
  # DELETE /quartz_photos/1.xml
  def destroy
    @quartz_photo = QuartzPhoto.find(params[:id])
    @quartz_photo.destroy

    respond_to do |format|
      format.html { redirect_to(quartz_photos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/quartz_photos_helper.rb
module QuartzPhotosHelper
end

app/views/quartz_photos/_form.html.erb
<%= form_for(@quartz_photo) do |f| %>
  <% if @quartz_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quartz_photo.errors.count, "error") %> prohibited this quartz_photo from being saved:</h2>

      <ul>
      <% @quartz_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quartz_id %><br />
    <%= f.text_field :quartz_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quartz_photos/edit.html.erb
<h1>Editing quartz_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @quartz_photo %> |
<%= link_to 'Back', quartz_photos_path %>

app/views/quartz_photos/index.html.erb
<h1>Listing quartz_photos</h1>

<table>
  <tr>
    <th>Quartz</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quartz_photos.each do |quartz_photo| %>
  <tr>
    <td><%= quartz_photo.quartz_id %></td>
    <td><%= link_to 'Show', quartz_photo %></td>
    <td><%= link_to 'Edit', edit_quartz_photo_path(quartz_photo) %></td>
    <td><%= link_to 'Destroy', quartz_photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quartz photo', new_quartz_photo_path %>

app/views/quartz_photos/new.html.erb
<h1>New quartz_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', quartz_photos_path %>

app/views/quartz_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quartz:</b>
  <%= @quartz_photo.quartz_id %>
</p>


<%= link_to 'Edit', edit_quartz_photo_path(@quartz_photo) %> |
<%= link_to 'Back', quartz_photos_path %>