config/routes.rb
Qcss::Application.routes.draw do

  namespace :silicon_metal do
    resources :gpos
  end

  namespace :silicon_metal do
    resources :pos
  end

  namespace :silicon_metal do
    resources :si_shippings
  end

  namespace :silicon_metal do
    resources :mix_bags
    resources :mix_bag_contents
  end

  namespace :purchase do
    resources :units
  end

  namespace :warehouse do
    resources :checkins
  end

  namespace :hr do resources :subcompanies end

  namespace :hr do resources :positions end

  namespace :hr do resources :dept_changes end

  namespace :ms do resources :bag_inventories end

  namespace :ms do resources :bags end

  namespace :hr do 
    resources :attendences do
      collection { post :import }
      collection do
        get :summary
      end
    end
  end
      
  
  namespace :power do resources :factors end

  namespace :power do resources :furnaces end

  namespace :power do 
    resources :totals do
      collection do
        get :summary
      end
    end 
  end

  namespace :hr do
    resources :otms do
      collection do
        get :summary
      end
    end
  end

  namespace :purchase do resources :locations end

  namespace :purchase do 
    resources :requests do
      collection do
        get :plan
        get :reject
        get :finish
        get :warehouse
        get :warehoused
        get :trace
        get :p_confirm
        get :all
      end
    end
  end
  
  namespace :purchase do resources :request_photos end

  resources :e_furnaces do
    collection do
      get :summary
    end
  end

  resources :rm_rates

  resources :security_case_media

  resources :security_cases

  resources :ms_reworks

  resources :vehicle_requests do
    collection do 
      get :planning
    end
  end

  resources :v_netweights

  resources :vehicle_dailies

  resources :weightings do
    collection do
      get :summary
    end
  end

  resources :vehicles

  resources :dailyreport_jobs

  resources :dailyreports do
    collection do
      get :daily_summary
    end
  end

  namespace :interviews do resources :its end

  resources :destinations

  resources :freights

  resources :payments

  resources :partical_sizes

  resources :po_controls do
    collection do
      get :po_search_result
    end
  end

  resources :ms_offgrades

  resources :si_inventory_contents

  resources :si_inventories do
    collection do
      get :si_inventory_report
      get :multiple_bags
      post :create_multiple
    end
  end

  resources :pickings

  resources :warehouse_item_photos

  resources :employeer_photos

  resources :employeers

  resources :it_reservations

  resources :quartz_photos

  resources :quartzs

  resources :ms_loadings do
    collection do
      get :loading_summary_search_result
    end
  end

  resources :ms_losses

  get "impress/microsilica"

  resources :ms_prod_confirms

  resources :silicashiplots

  resources :silicaships

  resources :sampleresults

  resources :oxygens

  resources :msshipbags

  resources :msshiplots

  resources :ms_shippments

  resources :charcoal_dusts

  resources :mssamples

  resources :samples

  resources :en_certifies

  resources :microsilicas

  resources :silos

  resources :env_monitors

  resources :it_devices

  resources :customers

  resources :complains

  resources :it_repairs

  resources :categories

  resources :departments

  resources :warehouse_suppliers

  resources :warehouse_items

  resources :suppliers

  resources :charcoals

  resources :coasilicons

  get "analysis/silicon"

  get "reports/daily"

  get "reports/period"
  
  get "reports/charcoalsum"

  get "summary/index"

  get "site/index"
  

  devise_for :users
  resources :users 
  resources :grades

  resources :silicons
  resources :coas
  

  root :to => "site#index"

  get ':controller(/:action(/:id(.:format)))'
  
end

app/models/rm_rate.rb
class RmRate < ActiveRecord::Base
end

app/controllers/rm_rates_controller.rb
class RmRatesController < ApplicationController
  # GET /rm_rates
  # GET /rm_rates.xml
  def index
    @rm_rates = RmRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rm_rates }
    end
  end

  # GET /rm_rates/1
  # GET /rm_rates/1.xml
  def show
    @rm_rate = RmRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rm_rate }
    end
  end

  # GET /rm_rates/new
  # GET /rm_rates/new.xml
  def new
    @rm_rate = RmRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rm_rate }
    end
  end

  # GET /rm_rates/1/edit
  def edit
    @rm_rate = RmRate.find(params[:id])
  end

  # POST /rm_rates
  # POST /rm_rates.xml
  def create
    params.permit!
    @rm_rate = RmRate.new(params[:rm_rate])

    respond_to do |format|
      if @rm_rate.save
        format.html { redirect_to(@rm_rate, :notice => 'Rm rate was successfully created.') }
        format.xml  { render :xml => @rm_rate, :status => :created, :location => @rm_rate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rm_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rm_rates/1
  # PUT /rm_rates/1.xml
  def update
    params.permit!
    @rm_rate = RmRate.find(params[:id])

    respond_to do |format|
      if @rm_rate.update_attributes(params[:rm_rate])
        format.html { redirect_to(@rm_rate, :notice => 'Rm rate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rm_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rm_rates/1
  # DELETE /rm_rates/1.xml
  def destroy
    @rm_rate = RmRate.find(params[:id])
    @rm_rate.destroy

    respond_to do |format|
      format.html { redirect_to(rm_rates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rm_rates_helper.rb
module RmRatesHelper
end

app/views/rm_rates/_form.html.erb
<%= form_for(@rm_rate) do |f| %>
  <% if @rm_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rm_rate.errors.count, "error") %> prohibited this rm_rate from being saved:</h2>

      <ul>
        <% @rm_rate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%#= f.label :code %><br />
    <%#= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate, :size=>"8" %> %
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rm_rates/edit.html.erb
<% if can? :manage, :rm_rate %>
<h2>Editing Raw Material Rate</h2>

<%= render 'form' %>

<%= link_to 'Show', @rm_rate %> |
<%= link_to 'Back', rm_rates_path %>

<% end %>

app/views/rm_rates/index.html.erb
<% if can? :manage, :rm_rate %>

  <h2>Listing Raw Materials' Rates</h2>

  <table>
    <tr>
      <th>Name | 原 料 名 称</th>
      <th>Rate | 配 比 <br/>( Unit : % )</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @rm_rates.each do |rm_rate| %>
      <tr>
        <td><%= rm_rate.name %></td>
        <td><%= rm_rate.rate %> % </td>
        <td><%#= button_to 'Show', rm_rate, :method=>:get %></td>
        <td><%= button_to 'Edit | 编 辑', edit_rm_rate_path(rm_rate), :method=>:get%></td>
        <td><%#= link_to 'Del', rm_rate, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%#= link_to 'New', new_rm_rate_path %>

<% end %>

app/views/rm_rates/new.html.erb
<% if can? :manage, :rm_rate %>

<h2>New Raw  Material Rate</h2>

<%= render 'form' %>

<%= link_to 'Back', rm_rates_path %>

<% end %>

app/views/rm_rates/show.html.erb
<% if can? :manage, :rm_rate %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rm_rate.name %>
</p>

<p>
  <b>Rate:</b>
  <%= @rm_rate.rate %>
</p>


<%= link_to 'Edit', edit_rm_rate_path(@rm_rate) %> |
<%= link_to 'Back', rm_rates_path %>

<% end %>