config/routes.rb
Qcss::Application.routes.draw do

  namespace :silicon_metal do
    resources :gpos
  end

  namespace :silicon_metal do
    resources :pos
  end

  namespace :silicon_metal do
    resources :si_shippings
  end

  namespace :silicon_metal do
    resources :mix_bags
    resources :mix_bag_contents
  end

  namespace :purchase do
    resources :units
  end

  namespace :warehouse do
    resources :checkins
  end

  namespace :hr do resources :subcompanies end

  namespace :hr do resources :positions end

  namespace :hr do resources :dept_changes end

  namespace :ms do resources :bag_inventories end

  namespace :ms do resources :bags end

  namespace :hr do 
    resources :attendences do
      collection { post :import }
      collection do
        get :summary
      end
    end
  end
      
  
  namespace :power do resources :factors end

  namespace :power do resources :furnaces end

  namespace :power do 
    resources :totals do
      collection do
        get :summary
      end
    end 
  end

  namespace :hr do
    resources :otms do
      collection do
        get :summary
      end
    end
  end

  namespace :purchase do resources :locations end

  namespace :purchase do 
    resources :requests do
      collection do
        get :plan
        get :reject
        get :finish
        get :warehouse
        get :warehoused
        get :trace
        get :p_confirm
        get :all
      end
    end
  end
  
  namespace :purchase do resources :request_photos end

  resources :e_furnaces do
    collection do
      get :summary
    end
  end

  resources :rm_rates

  resources :security_case_media

  resources :security_cases

  resources :ms_reworks

  resources :vehicle_requests do
    collection do 
      get :planning
    end
  end

  resources :v_netweights

  resources :vehicle_dailies

  resources :weightings do
    collection do
      get :summary
    end
  end

  resources :vehicles

  resources :dailyreport_jobs

  resources :dailyreports do
    collection do
      get :daily_summary
    end
  end

  namespace :interviews do resources :its end

  resources :destinations

  resources :freights

  resources :payments

  resources :partical_sizes

  resources :po_controls do
    collection do
      get :po_search_result
    end
  end

  resources :ms_offgrades

  resources :si_inventory_contents

  resources :si_inventories do
    collection do
      get :si_inventory_report
      get :multiple_bags
      post :create_multiple
    end
  end

  resources :pickings

  resources :warehouse_item_photos

  resources :employeer_photos

  resources :employeers

  resources :it_reservations

  resources :quartz_photos

  resources :quartzs

  resources :ms_loadings do
    collection do
      get :loading_summary_search_result
    end
  end

  resources :ms_losses

  get "impress/microsilica"

  resources :ms_prod_confirms

  resources :silicashiplots

  resources :silicaships

  resources :sampleresults

  resources :oxygens

  resources :msshipbags

  resources :msshiplots

  resources :ms_shippments

  resources :charcoal_dusts

  resources :mssamples

  resources :samples

  resources :en_certifies

  resources :microsilicas

  resources :silos

  resources :env_monitors

  resources :it_devices

  resources :customers

  resources :complains

  resources :it_repairs

  resources :categories

  resources :departments

  resources :warehouse_suppliers

  resources :warehouse_items

  resources :suppliers

  resources :charcoals

  resources :coasilicons

  get "analysis/silicon"

  get "reports/daily"

  get "reports/period"
  
  get "reports/charcoalsum"

  get "summary/index"

  get "site/index"
  

  devise_for :users
  resources :users 
  resources :grades

  resources :silicons
  resources :coas
  

  root :to => "site#index"

  get ':controller(/:action(/:id(.:format)))'
  
end

app/models/sampleresult.rb
#coding: utf-8
class Sampleresult < ActiveRecord::Base
  
  validates_uniqueness_of :week, :scope => [:week, :stype, :silo]
  
  
end

app/controllers/sampleresults_controller.rb
class SampleresultsController < ApplicationController
  # GET /sampleresults
  # GET /sampleresults.xml
  def index
    @sampleresults = Sampleresult.paginate :page => params[:page], :order => 'date DESC, week DESC, silo', :per_page=> 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sampleresults }
    end
  end

  # GET /sampleresults/1
  # GET /sampleresults/1.xml
  def show
    @sampleresult = Sampleresult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sampleresult }
    end
  end

  # GET /sampleresults/new
  # GET /sampleresults/new.xml
  def new
    @sampleresult = Sampleresult.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sampleresult }
    end
  end

  # GET /sampleresults/1/edit
  def edit
    @sampleresult = Sampleresult.find(params[:id])
  end

  # POST /sampleresults
  # POST /sampleresults.xml
  def create
    params.permit!
    @sampleresult = Sampleresult.new(params[:sampleresult])

    respond_to do |format|
      if @sampleresult.save
        format.html { redirect_to(@sampleresult, :notice => 'Sampleresult was successfully created.') }
        format.xml  { render :xml => @sampleresult, :status => :created, :location => @sampleresult }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sampleresult.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sampleresults/1
  # PUT /sampleresults/1.xml
  def update
    params.permit!
    @sampleresult = Sampleresult.find(params[:id])

    respond_to do |format|
      if @sampleresult.update_attributes(params[:sampleresult])
        format.html { redirect_to(@sampleresult, :notice => 'Sampleresult was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sampleresult.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sampleresults/1
  # DELETE /sampleresults/1.xml
  def destroy
    @sampleresult = Sampleresult.find(params[:id])
    @sampleresult.destroy

    respond_to do |format|
      format.html { redirect_to(sampleresults_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sampleresults_helper.rb
module SampleresultsHelper
end

app/views/sampleresults/_form.html.erb
<%= form_for(@sampleresult) do |f| %>
  <% if @sampleresult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sampleresult.errors.count, "error") %> prohibited this sampleresult from being saved:</h2>

      <ul>
        <% @sampleresult.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>>
  <% end %>

  <table>
    <tr/>
    <td  style="text-align : right;"/>Date:
    <td style="text-align : left;"/><%= f.text_field :date, :size=>"8", :class => "datePicker" %>


    <tr/>
    <td style="text-align : right;"/>Type:
    <td style="text-align : left;"/><%= f.collection_select :stype, %w[EN ASTM], :to_s, :upcase %>


    <tr/>
    <td style="text-align : right;"/>Week:
    <td style="text-align : left;"/><%= f.select :week, 1..54 %>


    <tr/>
    <td style="text-align : right;"/>Silo:
    <td style="text-align : left;"/><%= f.collection_select :silo, Silo::SILO, :to_s, :humanize %>


    <tr/>
    <td style="text-align : right;"/>H2O:
    <td style="text-align : left;"/><%= f.text_field :h2o, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Loi950:
    <td style="text-align : left;"/><%= f.text_field :loi, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>SiC:
    <td style="text-align : left;"/><%= f.text_field :sic, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>C:
    <td style="text-align : left;"/><%= f.text_field :c, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Density:
    <td style="text-align : left;"/><%= f.text_field :density, :size=>"8" %> Kg/dm3


    <tr/>
    <td style="text-align : right;"/>Sieve+0.045mm:
    <td style="text-align : left;"/><%= f.text_field :sieve, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Ph:
    <td style="text-align : left;"/><%= f.text_field :ph, :size=>"8" %>


    <tr/>
    <td style="text-align : right;"/>SiO2:
    <td style="text-align : left;"/><%= f.text_field :sio2 , :size=>"8"%> %


    <tr/>
    <td style="text-align : right;"/>Fe2O3:
    <td style="text-align : left;"/><%= f.text_field :fe, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Al2O3:
    <td style="text-align : left;"/><%= f.text_field :al, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>CaO:
    <td style="text-align : left;"/><%= f.text_field :ca, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>MgO:
    <td style="text-align : left;"/><%= f.text_field :mg, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Na2O:
    <td style="text-align : left;"/><%= f.text_field :na, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>K2O:
    <td style="text-align : left;"/><%= f.text_field :k, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>P2O5:
    <td style="text-align : left;"/><%= f.text_field :p, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>SO3:
    <td style="text-align : left;"/><%= f.text_field :s, :size=>"8" %> %


    <tr/>
    <td style="text-align : right;"/>Cl+:
    <td style="text-align : left;"/><%= f.text_field :cl, :size=>"8" %> %
  </table>


  <table>
    <tr/>
    <td/> <%= f.submit "提 交 | Submit" %>
  <% end %>
  <td style="text-align : left;"/><%= button_to '返 回 | Back', sampleresults_path, :method=>:get %>
</table>

app/views/sampleresults/edit.html.erb
<h2>Editing Sample Result</h2>

<% if can? :edit, :sampleresults %>

  <%= render 'form' %>

<% else %>

  <%= render 'site/denied' %>

<% end %>

app/views/sampleresults/index.html.erb
<table>
  <tr/><th style="font-size: 18px" />Summary Of Test Result
  <th/> 
  <div class="buttons">
    <input type="button" class="summary_result" value="点 击 查 看 | Show Detail">
  </div>
</table>

<div class="content_summary_result" style="display:none">

  <table>

    <tr/>
    <td/><% str_xml = render :file=> "sampleresults/data/sio2", :locals => {:sampleresults=>@sampleresults, :animate_chart => @animate_chart}
    render_chart root_url+'charts/FCF_MSLine.swf', '', str_xml, "sio2", 600, 220, false, false %>

    <tr/>
    <td/><% str_xml = render :file=> "sampleresults/data/ph", :locals => {:sampleresults=>@sampleresults, :animate_chart => @animate_chart }
    render_chart root_url+'charts/FCF_MSLine.swf', '', str_xml, "ph", 600, 220, false, false %>                  

    <tr/>
    <td/><% str_xml = render :file=> "sampleresults/data/others", :locals => {:sampleresults=>@sampleresults, :animate_chart => @animate_chart }
    render_chart root_url+'charts/FCF_StackedArea2D.swf', '', str_xml, "others", 600, 450, false, false %>                  

    <tr/><th/>

  </table>

</div>

<p/><p/>

<h2>Listing sample results</h2>

<table>
  <tr/>
  <% if can? :manage, :sampleresults %>
    <th/><%= button_to 'New Record', new_sampleresult_path, :method=>:get %>
  <% end %>
  <th/><%= will_paginate @sampleresults %>
</table>

<table>
  <tr>
    <th>Date</th>
    <th>Type</th>
    <th>Week</th>
    <th>Silo</th>
    <th colspan="3">Operations</th>

  </tr>

  <% @sampleresults.each do |sampleresult| %>
    <tr>
      <td><%= sampleresult.date %></td>
      <td><%= sampleresult.stype %></td>
      <td><%= sampleresult.week %></td>
      <td><%= sampleresult.silo %></td>

      <td><%= button_to '显 示 | Show', sampleresult, :method=>:get %></td>
      <% if can? :manage, :sampleresults %>
        <td><%= button_to '编 辑 | Edit', edit_sampleresult_path(sampleresult), :method=>:get %></td>
        <td><%= button_to '删 除 | Del', sampleresult, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />
<table>
  <tr/>
  <% if can? :manage, :sampleresults %>
    <th/><%= button_to 'New Record', new_sampleresult_path, :method=>:get %>
  <% end %>
  <th/><%= will_paginate @sampleresults %>
</table>

app/views/sampleresults/new.html.erb
<% if can? :create, :sampleresults %>
<h2>New Sample Result</h2>

<%= render 'form' %>

<% else %>

<%= render "site/denied" %>

<% end %>

app/views/sampleresults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @sampleresult.date %>
</p>

<p>
  <b>Type:</b>
  <%= @sampleresult.stype %>
</p>

<p>
  <b>Week:</b>
  <%= @sampleresult.week %>
</p>

<p>
  <b>Silo:</b>
  <%= @sampleresult.silo %>
</p>

<p>
  <b>H2O:</b>
  <%= @sampleresult.h2o %> %
</p>

<p>
  <b>Loi950:</b>
  <%= @sampleresult.loi %> %
</p>

<p>
  <b>SiC:</b>
  <%= @sampleresult.sic %> %
</p>

<p>
  <b>C:</b>
  <%= @sampleresult.c %> %
</p>

<p>
  <b>Density:</b>
  <%= @sampleresult.density %> Kg/dm3
</p>

<p>
  <b>Sieve +0.045mm:</b>
  <%= @sampleresult.sieve %> %
</p>

<p>
  <b>Ph:</b>
  <%= @sampleresult.ph %>
</p>

<p>
  <b>SiO2:</b>
  <%= @sampleresult.sio2 %> %
</p>

<p>
  <b>Fe2O3:</b>
  <%= @sampleresult.fe %>  %
</p>

<p>
  <b>Al2O3:</b>
  <%= @sampleresult.al %>  %
</p>

<p>
  <b>CaO:</b>
  <%= @sampleresult.ca %>  %
</p>

<p>
  <b>MgO:</b>
  <%= @sampleresult.mg %>  %
</p>

<p>
  <b>Na2O:</b>
  <%= @sampleresult.na %>  %
</p>

<p>
  <b>K2O:</b>
  <%= @sampleresult.k %>  %
</p>

<p>
  <b>P2O5:</b>
  <%= @sampleresult.p %>  %
</p>

<p>
  <b>SO3:</b>
  <%= @sampleresult.s %>  %
</p>

<p>
  <b>Cl+:</b>
  <%= @sampleresult.cl %>  %
</p>

<% if can? :edit, :sampleresults %>
  <%= button_to 'Edit', edit_sampleresult_path(@sampleresult), :method=>:get %>
<% end %>
<%= button_to 'Back', sampleresults_path, :method=>:get  %>