config/routes.rb
Qcss::Application.routes.draw do

  namespace :silicon_metal do
    resources :gpos
  end

  namespace :silicon_metal do
    resources :pos
  end

  namespace :silicon_metal do
    resources :si_shippings
  end

  namespace :silicon_metal do
    resources :mix_bags
    resources :mix_bag_contents
  end

  namespace :purchase do
    resources :units
  end

  namespace :warehouse do
    resources :checkins
  end

  namespace :hr do resources :subcompanies end

  namespace :hr do resources :positions end

  namespace :hr do resources :dept_changes end

  namespace :ms do resources :bag_inventories end

  namespace :ms do resources :bags end

  namespace :hr do 
    resources :attendences do
      collection { post :import }
      collection do
        get :summary
      end
    end
  end
      
  
  namespace :power do resources :factors end

  namespace :power do resources :furnaces end

  namespace :power do 
    resources :totals do
      collection do
        get :summary
      end
    end 
  end

  namespace :hr do
    resources :otms do
      collection do
        get :summary
      end
    end
  end

  namespace :purchase do resources :locations end

  namespace :purchase do 
    resources :requests do
      collection do
        get :plan
        get :reject
        get :finish
        get :warehouse
        get :warehoused
        get :trace
        get :p_confirm
        get :all
      end
    end
  end
  
  namespace :purchase do resources :request_photos end

  resources :e_furnaces do
    collection do
      get :summary
    end
  end

  resources :rm_rates

  resources :security_case_media

  resources :security_cases

  resources :ms_reworks

  resources :vehicle_requests do
    collection do 
      get :planning
    end
  end

  resources :v_netweights

  resources :vehicle_dailies

  resources :weightings do
    collection do
      get :summary
    end
  end

  resources :vehicles

  resources :dailyreport_jobs

  resources :dailyreports do
    collection do
      get :daily_summary
    end
  end

  namespace :interviews do resources :its end

  resources :destinations

  resources :freights

  resources :payments

  resources :partical_sizes

  resources :po_controls do
    collection do
      get :po_search_result
    end
  end

  resources :ms_offgrades

  resources :si_inventory_contents

  resources :si_inventories do
    collection do
      get :si_inventory_report
      get :multiple_bags
      post :create_multiple
    end
  end

  resources :pickings

  resources :warehouse_item_photos

  resources :employeer_photos

  resources :employeers

  resources :it_reservations

  resources :quartz_photos

  resources :quartzs

  resources :ms_loadings do
    collection do
      get :loading_summary_search_result
    end
  end

  resources :ms_losses

  get "impress/microsilica"

  resources :ms_prod_confirms

  resources :silicashiplots

  resources :silicaships

  resources :sampleresults

  resources :oxygens

  resources :msshipbags

  resources :msshiplots

  resources :ms_shippments

  resources :charcoal_dusts

  resources :mssamples

  resources :samples

  resources :en_certifies

  resources :microsilicas

  resources :silos

  resources :env_monitors

  resources :it_devices

  resources :customers

  resources :complains

  resources :it_repairs

  resources :categories

  resources :departments

  resources :warehouse_suppliers

  resources :warehouse_items

  resources :suppliers

  resources :charcoals

  resources :coasilicons

  get "analysis/silicon"

  get "reports/daily"

  get "reports/period"
  
  get "reports/charcoalsum"

  get "summary/index"

  get "site/index"
  

  devise_for :users
  resources :users 
  resources :grades

  resources :silicons
  resources :coas
  

  root :to => "site#index"

  get ':controller(/:action(/:id(.:format)))'
  
end

app/controllers/reports_controller.rb
#coding = utf-8

class ReportsController < ApplicationController
  
  
  layout "main", :except => :print
  
  def daily
 
    
    @quartz_rate=RmRate.where(:code=>"quartz").first.rate.to_i
    @charcoal_rate=RmRate.where(:code=>"charcoal").first.rate.to_i
    @wood_rate=RmRate.where(:code=>"wood").first.rate.to_i
    @coke_rate=RmRate.where(:code=>"coke").first.rate.to_i
    
    # 生成生產日報表
    
    if params[:date]
      date = params[:date].to_date
      #sdate = Date.civil(params[:date][:"(1i)"].to_i,params[:date][:"(2i)"].to_i,params[:date][:"(3i)"].to_i)
      @silicons = Silicon.select("id, fe, al, ca, ti, p, b, furnace, grade, weight, shift, no, date, remark, t_point").where("date=?", date).order( 'furnace, date DESC, shift, no')
      @silicons_yesterday = Silicon.where("date=?", date.yesterday).order( 'furnace, date DESC, shift, no')
    end
    
    @date_select = date
    
    @expense = EFurnace.where("date=?", @date_select)
    
    @total_power=@expense.sum(:s1_e)+@expense.sum(:s2_e)+@expense.sum(:s3_e)
    @total_quartz=@expense.sum(:s1_q)+@expense.sum(:s2_q)+@expense.sum(:s3_q)
    @total_charcoal=@expense.sum(:s1_ch)+@expense.sum(:s2_ch)+@expense.sum(:s3_ch)
    @total_wood=@expense.sum(:s1_w)+@expense.sum(:s2_w)+@expense.sum(:s3_w)
    @total_coke=@expense.sum(:s1_c)+@expense.sum(:s2_c)+@expense.sum(:s3_c)
    
    @furnace = @silicons.group_by { |s|s.furnace }
    @furnace_yesterday = @silicons_yesterday.group_by { |s|s.furnace }
    
    @si_packing = SiInventoryContent.where(:p_date=>@date_select)
    
  end
  
  
  def period
    
    @grades = Grade.all
    # 某時間區間內的生產報表
  
    #############判断时间区间############################
    if params[:start_date] && params[:end_date]   
      
      @start_date = params[:start_date].to_date
      @end_date = params[:end_date].to_date
      
      @date_period = @start_date..@end_date
      
    end
    
    # Packing info at this period
    @si_packing_period = SiInventoryContent.where(:p_date=>@date_period)
    
    
     
    #判断等级
    if params[:grade]==""
      @grade=[]
      @grades.each do |g|
        @grade << g.name
      end
      @grade_type = "所 有 等 级 | All Grade"
    else      
      @grade = params[:grade]
      @grade_type = @grade  
    end
    
    ################判断铁，铝，钙含量###################
       
    #    @fe = sprintf("%0.3f ", params[:fe].to_f*10000).to_s
    #    @al = sprintf("%0.3f ", params[:al].to_f*10000).to_s
    if params[:fe]==""
      @fe = (0...1000000)
    else
      @fe = (0...params[:fe].to_f*10000)
    end
    
    if params[:al]==""
      @al = (0...1000000)
    else
      @al = (0...params[:al].to_f*10000)
    end
    
    if params[:ca]==""
      @ca = (0...1000000)
    else
      @ca = (0...params[:ca].to_f*10000)
    end
    
    ##################参数检索###################
    @silicons=Silicon.select("id, fe, al, ca, ti, furnace, grade, weight, shift, no, date, remark, operator, sampler").where(:date=>@date_period, :grade => @grade, :fe=>@fe, :al=>@al, :ca=>@ca ).order( 'furnace, date DESC, shift DESC, no DESC')
    #@silicons=Silicon.where("").order( 'furnace, date DESC, shift, no')
    #@silicons=Silicon.find_by_sql(["SELECT * FROM silicons WHERE date BETWEEN ? AND ? " , @start_date, @end_date])
    @furnace = @silicons.group_by { |a|a.furnace}
    @date = @silicons.group_by { |a|a.date }.sort
    @silicon_date_monthly = @silicons.group_by { |s|s.date.strftime("%Y-%m") }
  
    
    @expense = EFurnace.where(:date=>@date_period).order('date')
    @expense_date = @expense.group_by { |e|e.date  }
    
    
    
  end
  
  
  def search
    
    # 金屬硅檢索
    
    #    if params[:fur] && params[:date]&& params[:shift]&& params[:no]
    #          
    #      furnace = params[:fur]
    #      date = Date.civil(params[:date][:"(1i)"].to_i,params[:date][:"(2i)"].to_i,params[:date][:"(3i)"].to_i)
    #      shift = params[:shift]
    #      no = params[:no]
    #          
    #      @silicon = Silicon.where( :date=>date, :furnace=>furnace, :shift=>shift, :no=>no)
    #    
    #    end
  end
  
  def search_result ## Search from QC
    
    if params[:sicodes] && params[:weight]
      
      @weight = params[:weight][0]

      @sicodes = params[:sicodes][0].split(/\r\n/) #[0] means select the first element from this array.
      
      @silicons = []
      @pack_bag_ids_all = []
      
      
      @sicodes.each do |sc|        
       
        @silicon = Silicon.where( "date=? && furnace=? && shift=? && no=? ","20"+sc[5,2]+"-"+sc[7,2]+"-"+sc[9,2],sc[3,1], sc[12,1], sc[14,1])            
        @silicons << @silicon  

        @si_packing = SiInventoryContent.select('si_inventory_id').where(p_date: "20"+sc[5,2]+"-"+sc[7,2]+"-"+sc[9,2], furnace: sc[3,1], shift: sc[12,1], no: sc[14,1] )
        @pack_bag_ids=[]
        @si_packing.each do |si|
          @pack_bag_ids << si.si_inventory_id
        end
        @pack_bag_ids_all<<@pack_bag_ids
      end            
      
    end
    
  end
  
  
  
  
  def search_result_wh ## Search from warehouse 
    
    if (params[:wh_date] && params[:p_date] && params[:location] && params[:gpo_code] && params[:container_no] && params[:sicodes]) == ["*"]
      @silicon_bags = [""]
      @silicon_feedback = "Please identify at least one condition. | 请先定义一个检索条件"
    else
      if params[:wh_date] && params[:p_date] && params[:location] && params[:gpo_code] && params[:container_no] && params[:sicodes]
      
        @sicodes = params[:sicodes][0].split(/\r\n/) #[0] means select the first element from this array.
        @wh_date = params[:wh_date]
        @p_date = params[:p_date]
        @location = params[:location]
        @gpo_code = params[:gpo_code]
        @container_no = params[:container_no]
      
        ############# Start to check condition p_date ###########
        if @p_date == [""]
          @si_wh_p = SiInventory.where("date IS NULL OR date = ?", "")
        elsif @wh_date == ["*"]
          @si_wh_p = SiInventory.all
        else
          @si_wh_p = SiInventory.where("date = ?", @p_date)
          # end # end of if=="*"d
        end # end of if.nil?
        ########### Finish p_date checking  ####################
    
        
        ############# Start to check condition wh_date ###########
        if @wh_date == [""]
          @si_wh_d = @si_wh_p.where("wh_date IS NULL OR wh_date = ?", "")
        elsif @wh_date == ["*"]
          @si_wh_d = SiInventory.all
        else
          @si_wh_d = @si_wh_p.where("wh_date = ?", @wh_date)
          # end # end of if=="*"d
        end # end of if.nil?
        ########### Finish wh_date checking  ####################
    
        ########### Start to check condition location ###########
        if @location == [""]
          @si_wh_dl = @si_wh_d.where("location IS null OR location = ?", "")
        else
          if @location == ["*"]
            @si_wh_dl = @si_wh_d
          else
            @si_wh_dl = @si_wh_d.where("location = ?", @location)
          end # end of if=="*"d
        end # end of if.nil?
        ########### Finish location checking  ####################
    
        ########### Start to check condition gpo_code ###########
        if @gpo_code == [""]
          @si_wh_dlg = @si_wh_dl.where("gpo_code IS null OR gpo_code = ?", "")
        else
          if @gpo_code == ["*"]
            @si_wh_dlg = @si_wh_dl
          else
            @si_wh_dlg = @si_wh_dl.where("gpo_code = ? OR gpo_production = ?", @gpo_code, @gpo_code )
          end # end of if=="*"d
        end # end of if.nil?
        ########### Finish gpo_code checking  ####################
    
        ########### Start to check condition container_no ###########
        if @container_no == [""]
          @si_wh_dlgc = @si_wh_dlg.where("container_no IS null OR container_no = ?", "")
        else
          if @container_no == ["*"]
            @si_wh_dlgc = @si_wh_dlg
          else
            @si_wh_dlgc = @si_wh_dlg.where("container_no = ?", @container_no)
          end # end of if=="*"d
        end # end of if.nil?
        ########### Finish container_no checking  ####################
    
        ########### Start to check condition silicon bag no. ####### 
      
      
        if params[:sicodes] == [""]
          @silicon_bags = @si_wh_dlgc
        else
        
          @silicon_bags = [] rescue nil
          @silicon_bags_mix= [] rescue nil
        
          @sicodes.each do |sc|  # sc[5,2] star from 5th element not inclued, select 2 elements after that.  

            if sc.size > 10
              silicon_bag = @si_wh_dlgc.where("date=? && furnace=? && shift=? && no=? && bag=? ","20"+sc[5,2]+"-"+sc[7,2]+"-"+sc[9,2],sc[3,1], sc[12,1], sc[14,1], sc[16,3] ).first 
              
              if silicon_bag.nil?
                silicon_bag_mix = SiliconMetal::MixBag.where("bag_no=?", sc).includes(:mix_bag_contents).first
              end
              
            else
              silicon_bag = @si_wh_dlgc.where( "bag_no=?", sc[0,4]+sc[5,5] ).first              
            end
        
            @silicon_bags << silicon_bag unless silicon_bag.nil?    
            @silicon_bags_mix << silicon_bag_mix unless silicon_bag_mix.nil?
          end # end of @sicodes.each 
        end # end if params[:sicodes].nil? 
      
      end # if params
      
    end # if everything ==[""]["*"]
  
  end # end of def
  
  
  
  
  def charcoalsum
    
    # 建立破碎統計表
    # 
  
    if params[:crash_sum_form]
      @charcoals = Charcoal.where("crash_sum_form=?", params[:crash_sum_form] )
    end
    
    @charcoalsum = @charcoals.group_by { |c|c.crash_sum_form  }
    @supplier = @charcoals.group_by { |c|c.su_code  }
    
  end
  
  ################################ Microsilica Report ###########################
  
  def ms_report
    
    @grades = Grade.where(:product=>"microsilica")
    @normal = " 无异常 | Normal | ปกติ "
    
    # 某時間區間內的生產報表
  
    ############# 判 断 时 间 区 间 ############################

app/helpers/reports_helper.rb
module ReportsHelper
  
  
  
end

app/views/reports/charcoalsum.html.erb
<% if can? :view, :charcoals %>

  <% @charcoalsum.each do |crash_sum_form,c| %>


    <!--sprint-1-->
    <font   size="4pt" >
    <table align="center" >
      <tr align="center" HEIGHT=40 ><th colspan="10"/>G.S.Energy Co.,Ltd 木 炭 質 量 統 計 表 <%= @date_select %></tr>
    </table>
    </font>
    GQ-07-002
    <table border="1px" align="center" cellspacing="0" cellpadding="0" width="740">  
      <tr align="center" HEIGHT=40 >

        <th colspan="3"/>检 验 报 告 编 号 : GQ-07-002-<%= crash_sum_form %>
        <% @supplier.each do |su_code,s| %>
          <th colspan="3"/>供 應 商 | Supplier : <%= su_code %> | <%= Supplier.where("code=?", su_code).first.name %>
        <% end %>
      </tr> 

      <tr HEIGHT=5>
        <th colspan="6"/>
      </tr>

      <tr align="center" HEIGHT=50 >
        <th/>序 號<br/>Item
      <th/>收 料 日<br/>Date
      <th/>車 牌 號 碼<br/>Truck NO.
      <th/>地 磅 單 序 號<br/>Form Code
      <th/>木 炭 重 量<br/>Weight
      <th/>檢 驗 報 告 編 號<br/>Test Report Code
    </tr>
    <% c.each_with_index do |c, index|  %>
      <tr align="center" HEIGHT=30 >
        <td/><%= index+1 %>
        <td/><%= c.date %>
        <td/><%= c.truck_no %>
        <td/><%= c.weightbridge_code %>
        <td/><%= c.weight %>
        <td/><%= link_to "GQ-07-001-05-#{c.form_code}", charcoal_path(c.id) %>
      </tr>
    <% end %>

    <tr HEIGHT=5>
      <th colspan="6"/>
    </tr>

    <tr align="center" HEIGHT=50>
      <th colspan="2"/>總 重 量<br/>Total Weight
    <th colspan="2"/>顆 粒 總 重 量<br/>Total Partical Weight
    <th colspan="2"/>測 試 結 果<br/>Test Result
    </tr>
    <tr align="center" HEIGHT=30>
      <td colspan="2"/><%= @total_weight = @charcoalsum[crash_sum_form].collect.sum(&:weight) %> Kg
      <td colspan="2"/><%= @total_pw = @charcoalsum[crash_sum_form].collect.sum(&:partical_weight) %> Kg
      <td colspan="2"/><%= sprintf( "%0.2f", @total_pw*100.0/@total_weight) %> %
    </tr>

    <tr align="center" HEIGHT=30>
      <th colspan="3"/>檢 驗 分 析 員 | ผู้ตรวจสอบ   
      <th colspan="3"/>負 責 人 | หัวหน้าแผนก
    </tr>
    <tr HEIGHT=30>
      <td colspan="3"/>   
      <td colspan="3"/>
    </tr>
    </table>
    GQ-07-002
  <% end %>
  <!--eprint-1-->

  <table>
    <tr/><th/>
    <% if can? :manage, :charcoals %>
      <input name="print" value="打 印 / Print" type="button" url=="javascript:;" onClick="doPrint('1')"/>
    <% end %>
  </table>

<% else %>
  <%= render 'site/denied' %>
<% end %>

app/views/reports/search_result_wh.html.erb
<% if can? :edit, :si_inventory_bag_location %>

  <table>
    <tr>
      <th colspan="11">Warehouse Information Of Silicon Bags</th>
    </tr>
    <tr>
      <th>Index</th>
      <th>Code</th>
      <th>Original<br/>Weight<br>Unit : Kg</th>
      <th>Current<br/>Weight<br>Unit : Kg</th>
      <th>Grade</th>
      <th>WH<br>Date</th>
      <th>Location</th>
      <th>G.P.O.</th>
      <th>Container NO.</th>
      <th>Operation</th>
    </tr>
    <% @silicon_bags.each_with_index do |(s),i|  %>
      <% if s.date < "2014-01-05".to_date %>
        <%  bag_no = 'GS-'+"#{s.furnace rescue nil}" +'-'+"#{s.date.strftime("%y%m%d") rescue nil}" +'-'+"#{s.shift rescue nil}"+'-'+"#{s.no rescue nil}" +'-'+"#{s.bag rescue nil}" %>
      <% else %>
        <% bag_no = "#{ s.bag_no[0,4] + '-' + s.bag_no[4,5]}" rescue nil %>
      <% end %>  
      <% weight_mix = SiliconMetal::MixBagContent.where("old_bag_no=?",bag_no).sum(:weight) rescue nil  %>
      <% final_weight = s.weight-weight_mix %>  
      <tr>
        <td><%= i+1 %></td>

        <td><%= bag_no rescue nil %></td>
        <td><%= s.weight rescue nil %></td>
        <td><%= final_weight rescue nil %></td>
        <td><%= if s.si_inventory_contents.count > 1 then "#{s.grade} - Ⓑ" else s.grade end rescue nil %></td>
        <td><%= s.wh_date rescue nil %></td>
        <td><%= s.location rescue nil %></td>
        <td><%= s.gpo_code rescue nil %><%= s.gpo_production rescue nil %></td>
        <td><%= s.container_no rescue nil %></td>
        <td><%= button_to "Edit", {:controller => "si_inventories", :action => "warehouse_edit", :id => s.id }, :method=>:get, :onclick => "this.form.target = 'warehouse_edit'; window.open('si_inventories','warehouse_edit', 'height = 550, width = 650, top = 10, left = 20, scrollbars = 0, toolbar = 0, status = 0, menubar = 0, location = 0')" rescue nil %></td>
      </tr>

    <% end %>
  </table>


<% end %>





<% if can? :search, :silicons %>
  <table>
    <tr>
      <th colspan="11">Chemical Elements Of Silicon Bags Content</th>
    </tr>

    <tr>
      <th>Code</th>
      <th>Weight<br>Unit : Kg</th>
      <th>Grade</th>
      <th>Date</th>
      <th>Fe %</th>
      <th>Al %</th>
      <th>Ca %</th>
      <th>Ti %</th>
      <th>P<br>ppm</th>
      <th>B<br>ppm</th>
      <th></th>
    </tr>
    <% @silicon_bags.each_with_index do |(s),i|  %>
      <% @si_inventory = SiInventory.find(s.id) rescue nil %>
      <% @element=[] rescue nil %>
      <% unless @si_inventory.nil? %>
        <% @si_inventory.si_inventory_contents.each do |si| %>
          <% @si_content = Silicon.where(:date=>si.p_date, :furnace=>si.furnace, :shift=>si.shift, :no=>si.no).first rescue nil %>
          <% @rate = (si.weight.to_i/@si_inventory.weight.to_f).round(5) rescue nil %>  
          <% @element << [ 
            (@si_content.fe*@rate rescue nil).to_i,  
            (@si_content.al*@rate rescue nil).to_i,
            (@si_content.ca*@rate rescue nil).to_i,
            (@si_content.ti*@rate rescue nil).to_i,
            (@si_content.p*@rate rescue nil).to_i,
            (@si_content.b*@rate rescue nil).to_i,
            (@si_content.na*@rate rescue nil).to_i,
            (@si_content.cu*@rate rescue nil).to_i,
            (@si_content.ni*@rate rescue nil).to_i,
            (@si_content.mn*@rate rescue nil).to_i,
            (@si_content.sn*@rate rescue nil).to_i,
            (@si_content.k*@rate rescue nil).to_i,
            (@si_content.pb*@rate rescue nil).to_i,
            (@si_content.v*@rate rescue nil).to_i,
            (@si_content.cr*@rate rescue nil).to_i,
            (@si_content.zn*@rate rescue nil).to_i,
            (@si_content.s*@rate rescue nil).to_i 
            ] %>

        <% end  %> 
      <% end #end of unless %>

      <tr>
        <% if @sicodes.present?%>
          <td><%= if s.nil? then @sicodes[i] else link_to "#{@sicodes[i]}", si_inventory_path(s.id) end %></td>   
        <% else %>
          <td>
            <% if s.furnace.blank? %>
              <%= link_to "#{ s.bag_no[0,4] + '-' + s.bag_no[4,5]}", edit_si_inventory_path(s) rescue nil %>
            <% else %>
              GS-<%= s.furnace rescue nil %>-<%= s.date.strftime("%y%m%d") rescue nil %>-<%= s.shift rescue nil %>-<%= s.no rescue nil %>-<%= s.bag rescue nil %>
            <% end %>
          </td>
        <% end %>
        <td><%= s.weight rescue nil %></td>
        <td><%= if s.si_inventory_contents.count > 1 then "#{s.grade} - Ⓑ" else s.grade end rescue nil %></td>
        <td><%= s.date rescue nil %></td>
        <td><%= (@element.transpose.map(&:sum)[0].to_f/10000).round(3) rescue nil%></td> 
        <td><%= (@element.transpose.map(&:sum)[1].to_f/10000).round(3) rescue nil%></td> 
        <td><%= (@element.transpose.map(&:sum)[2].to_f/10000).round(3) rescue nil%></td> 
        <td><%= (@element.transpose.map(&:sum)[3].to_f/10000).round(3) rescue nil%></td> 
        <td><%= (@element.transpose.map(&:sum)[4].to_f).round(3) rescue nil%></td> 
        <td><%= (@element.transpose.map(&:sum)[5].to_f).round(3) rescue nil%></td>
      </tr>  
    <% end%>
  </table>

  <table>
    <tr>
      <th colspan="5">Silicon No. Of Bags</th>
    </tr>
    <tr>
      <th>Index</th>
      <th>Bag No.</th>
      <th>Silicon No.</th>
      <th>Weight<br/>Unit : Kg</th>
      <th>Operator</th>
    </tr>
    <% @silicon_bags.each_with_index do |(s),i|  %>
      <% if s.date < "2014-01-05".to_date %>
        <% bag_no = 'GS-'+"#{s.furnace rescue nil}" +'-'+"#{s.date.strftime("%y%m%d") rescue nil}" +'-'+"#{s.shift rescue nil}"+'-'+"#{s.no rescue nil}" +'-'+"#{s.bag rescue nil}" %>
      <% else %>
        <% bag_no = "#{ s.bag_no[0,4] + '-' + s.bag_no[4,5]}" rescue nil %>
      <% end # end of if s.date %>  
      <% @si_inventory = SiInventory.find(s.id) rescue nil %>
      <% si_count = @si_inventory.si_inventory_contents.count %>
      <% unless @si_inventory.nil? %>
        <tr>
          <td rowspan =<%= "#{si_count+1}" %>><%= i+1 %></td>
          <td rowspan =<%= "#{si_count+1}" %>><%= bag_no rescue nil %></td>
        </tr>
        <% @si_inventory.si_inventory_contents.each do |si| %>
          <% sc_no= "GS-#{ si.furnace rescue nil }-#{si.p_date.strftime("%y%m%d") rescue nil }-#{si.shift rescue nil}-#{ si.no rescue nil}" %>
          <tr>
            <td><%= sc_no rescue nil %></td>
            <td><%= si.weight rescue nil %></td>
            <td>G<%= si.employee_code rescue nil %></td>    
          </tr>
        <% end #end of @si_inventory.si_inventory_contents %>
        <tr><td colspan="5"></td></tr>
      <% end  # end of unless %>

    <% end rescue nil # end of @silicon_bags.each_with_index%>

  </table>


  <table>
    <tr>
      <th colspan="4">Mix Bags</th>
    </tr>
    <tr>
      <th>Index</th>
      <th>Code</th>
      <th>Weight<br/>Unit:Kg</th>
      <th>Operation</th>
    </tr>
    <% @silicon_bags_mix.each_with_index do |sm,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= sm.bag_no rescue nil %></td>
        <td><%= sm.mix_bag_contents.sum(:weight) rescue nil %></td>
        <td><%= button_to 'Show', sm, method: :get rescue nil %></td>
      </tr>
    <% end rescue nil %>
  </table>




  --------------------------------------------------------------------------<p/>
  For Debug Only : <%= @wh_date %><br/>
  Date : <%= @si_wh_d.count %><br/>
  Date-Location : <%= @si_wh_dl.count %><br/>
  Date-Location-GPO : <%= @si_wh_dlg.count %><br/>
  Date-Location-GPO-Container : <%= @si_wh_dlgc.count %><br/>
  Final : <%= @silicon_bags.count %>

<% else %>
  <%= render 'site/denied' %>
<% end %>